# Default configuration parameters

DEFAULT_ALPHA = 0.01
DEFAULT_L1_RATIO = 0.3
DEFAULT_POWER = 0.8
DEFAULT_ALPHA_TEST = 0.05
DEFAULT_COEF_THRESHOLD = 1e-4
DEFAULT_TRAIN_TEST_SPLIT = 0.25
DEFAULT_N_BOOT = 2000
DEFAULT_MAX_DAYS = 60
DEFAULT_MDE = 0.01